/* Fictionalized Lisa Manoban career-life simulator. Gameplay events, relationships, schedules, finances and private-life situations are invented mechanics. */
const KEY='lisaLifeSimulatorSaveV1', MONTHS=['January','February','March','April','May','June','July','August','September','October','November','December'], DAYS=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const LEVELS=[['Trainee',0,'Training and small opportunities'],['Rising Artist',20,'More creative and media work'],['Idol',40,'Concerts and campaigns'],['Solo Artist',55,'Solo releases and major campaigns'],['International Star',70,'International projects'],['Global Superstar',85,'Elite global opportunities'],['Entertainment Icon',96,'Legacy opportunities']];
const PLACES={Seoul:[0,3,5,5],Bangkok:[1200,2,4,4],Paris:[8500,5,3,4],Milan:[7600,5,3,3],London:[6200,4,5,4],'New York':[7200,4,5,5],'Los Angeles':[6800,4,5,5],Tokyo:[5400,4,4,5],Dubai:[5000,5,3,4]};
const S={day:1,month:1,year:2026,age:20,location:'Seoul',money:100000,fame:25,happiness:80,energy:90,stress:10,musicSkill:60,danceSkill:85,fashionSkill:70,actingSkill:40,socialMedia:55,followers:500000,likesToday:0,engagement:0,reputation:70,careerLevel:2,totalDays:1,currentSong:null,releases:[],transactions:[],notifications:[],relationships:[{name:'Mina Park',role:'Dance Director',trust:64,friendship:70,chemistry:78},{name:'Evan Cole',role:'Fictional Producer',trust:58,friendship:49,chemistry:84},{name:'Nora Kim',role:'Fashion Editor',trust:72,friendship:61,chemistry:67},{name:'Jae Han',role:'Fictional Actor',trust:55,friendship:66,chemistry:60}]};
const STATS=[['happiness','❤️','Happiness'],['energy','⚡','Energy'],['fame','⭐','Fame'],['musicSkill','🎤','Music Skill'],['danceSkill','💃','Dance Skill'],['fashionSkill','👗','Fashion'],['actingSkill','🎬','Acting'],['socialMedia','📱','Social Media'],['money','💰','Money'],['stress','🧠','Stress']];
const A={
record:['Record Song','Music','Energy −12 • Music +2',()=>chg({energy:-12,musicSkill:2,stress:4})],vocals:['Practice Vocals','Music','Energy −8 • Music +3',()=>chg({energy:-8,musicSkill:3,stress:2})],write:['Write Music','Music','Energy −6 • Music +2 • Happiness +2',()=>chg({energy:-6,musicSkill:2,happiness:2,stress:1})],dance:['Dance Practice','Dance','Energy −15 • Dance +3 • Fame +1',()=>chg({energy:-15,danceSkill:3,fame:1,stress:5})],choreo:['Choreography','Dance','Energy −12 • Dance +4',()=>chg({energy:-12,danceSkill:4,musicSkill:1,stress:5})],rehearsal:['Rehearsal','Career','Energy −18 • Fame +2 • Stress +7',()=>chg({energy:-18,fame:2,stress:7})],
concert:['Concert','Career','Energy −25 • Fame +6 • Income',()=>{let n=rnd(18000,90000)+S.fame*700;chg({energy:-25,fame:6,happiness:5,stress:12});cash(n,'Concert');note('SHOW NIGHT','A fictional concert brought strong attendance.') }],fanmeet:['Fan Meeting','Career','Energy −12 • Fame +2 • Followers',()=>{let n=rnd(3000,18000);chg({energy:-12,fame:2,happiness:6,stress:3});S.followers+=n;note('FAN MILESTONE','+'+fmt(n)+' fictional followers.') }],interview:['Interview','Career','Energy −8 • Fame +2 • Reputation',()=>chg({energy:-8,fame:2,reputation:2,stress:3})],photoshoot:['Photoshoot','Fashion','Energy −10 • Fashion +3 • Fame +2',()=>chg({energy:-10,fashionSkill:3,fame:2,reputation:1,stress:4})],campaign:['Brand Campaign','Fashion','Energy −14 • Fame +4 • Income',()=>{let n=rnd(25000,140000)+S.fashionSkill*500;chg({energy:-14,fame:4,reputation:3,stress:8});cash(n,'Fictional campaign')}],audition:['Audition','Acting','Energy −10 • Acting +2',()=>{chg({energy:-10,actingSkill:2,stress:4});if(Math.random()<.35){chg({fame:3});note('CALLBACK','A fictional casting team requested a second meeting.')}}],acting:['Acting Project','Acting','Energy −20 • Acting +5 • Fame +5 • Income',()=>{let n=rnd(20000,110000);chg({energy:-20,actingSkill:5,fame:5,stress:9});cash(n,'Acting project')}],fashionweek:['Fashion Week','Fashion','Energy −18 • Fashion +4 • Fame +5',()=>chg({energy:-18,fashionSkill:4,fame:5,reputation:4,stress:10})],luxury:['Luxury Campaign','Fashion','Energy −15 • Fashion +4 • Fame +4 • Income',()=>{let n=rnd(50000,180000);chg({energy:-15,fashionSkill:4,fame:4,reputation:4,stress:8});cash(n,'Luxury campaign')}],magazine:['Magazine Cover','Fashion','Energy −8 • Fashion +2 • Fame +3',()=>chg({energy:-8,fashionSkill:2,fame:3,reputation:3,stress:3})],redcarpet:['Red Carpet','Fashion','Energy −10 • Fame +3 • Reputation +3',()=>chg({energy:-10,fame:3,reputation:3,stress:5})],rest:['Rest','Lifestyle','Energy +28 • Stress −12 • Happiness +5',()=>chg({energy:28,stress:-12,happiness:5})],exercise:['Exercise','Lifestyle','Energy −7 • Stress −5 • Happiness +4',()=>chg({energy:-7,stress:-5,happiness:4})],shopping:['Shopping','Lifestyle','Money −$3,200 • Happiness +6',()=>{if(S.money<3200)return note('NOT ENOUGH FUNDS','This fictional expense is outside your balance.');cash(-3200,'Shopping');chg({happiness:6,stress:-2})}],friends:['Spend Time With Friends','Lifestyle','Energy −5 • Happiness +9 • Stress −7',()=>chg({energy:-5,happiness:9,stress:-7})],private:['Private Time','Lifestyle','Energy +8 • Happiness +6 • Stress −10',()=>chg({energy:8,happiness:6,stress:-10})]};
function rnd(a,b){return Math.floor(Math.random()*(b-a+1))+a} function fmt(n){return Math.round(n).toLocaleString('en-US')} function clamp(n){return Math.max(0,Math.min(100,Math.round(n)))}
function date(){return new Date(S.year,S.month-1,S.day)} function label(){let d=date();return `${MONTHS[d.getMonth()].slice(0,3)} ${d.getDate()}, ${d.getFullYear()}`} function longDate(){let d=date();return `${d.getDate()} ${MONTHS[d.getMonth()].toUpperCase()} ${d.getFullYear()}`}
function cash(n,why){S.money=Math.max(0,S.money+n);S.transactions.unshift({amount:n,reason:why,date:label()});S.transactions=S.transactions.slice(0,40);ui()}
function chg(d){for(const k in d){if(k==='followers'||k==='likesToday'||k==='money')S[k]+=d[k];else if(k in S)S[k]=clamp(S[k]+d[k])}ui();milestones()}
function note(title,text){toast(title,text)}
function advanceDay(n=1,silent=false){for(let i=0;i<n;i++){let d=date();d.setDate(d.getDate()+1);S.day=d.getDate();S.month=d.getMonth()+1;S.year=d.getFullYear();S.totalDays++;if(S.totalDays%365===0)S.age++;S.energy=clamp(S.energy+8);S.stress=clamp(S.stress-3);S.happiness=clamp(S.happiness-1);S.likesToday=0;if(Math.random()<.18)event();if(Math.random()<.08)cash(-1200,'Staff & lifestyle')}ui();if(!silent)note('TIME ADVANCED',`You moved forward ${n===1?'one day':n+' days'}.`);save(true)}
function doAction(k){if(!A[k])return;if(S.energy<=0&&k!=='rest')return note('TOO EXHAUSTED','Rest before another demanding action.');A[k][3]();if(k!=='rest')advanceDay();note(A[k][0].toUpperCase(),'Action completed.');}
function createSong(){let title=(document.getElementById('songTitle').value||'Untitled Track').trim(),genre=document.getElementById('songGenre').value;S.currentSong={title,genre,bonus:rnd(0,8),recorded:false};music();note('SONG CREATED',`“${title}” is ready for recording.`)}
function recordSong(){if(!S.currentSong)return note('CREATE A SONG','Create your next fictional release first.');if(S.energy<10)return note('TOO EXHAUSTED','Rest before recording.');S.currentSong.recorded=true;chg({energy:-10,musicSkill:2,stress:5});music();note('RECORDING COMPLETE','Your song is ready for release.')}
function releaseSong(){let s=S.currentSong;if(!s)return note('NO SONG READY','Create and record a song first.');if(!s.recorded)return note('RECORD FIRST','Record the song before releasing it.');if(S.energy<12)return note('TOO EXHAUSTED','Rest before releasing a project.');let q=clamp(S.musicSkill+s.bonus+S.fame*.35+rnd(-10,12)),streams=Math.max(10000,Math.floor((q+S.fame)*rnd(180000,520000))),fans=Math.floor(streams*(.001+S.socialMedia/100000)),rev=Math.floor(streams*.0022),fg=Math.max(2,Math.floor(q/15)),review=q>82?'Acclaimed':q>65?'Strong':'Mixed';S.releases.unshift({title:s.title,genre:s.genre,streams,fans,revenue:rev,fameGain:fg,review,date:label()});S.followers+=fans;chg({energy:-12,fame:fg,happiness:5,stress:8});cash(rev,'Music release');S.currentSong=null;music();note('NEW SINGLE RELEASED',`“${s.title}” reached ${fmt(streams)} fictional streams • +$${fmt(rev)} • +${fmt(fans)} fans.`);advanceDay()}
function social(k){if(S.energy<5)return note('TOO EXHAUSTED','Rest before posting.');let x={photo:[2,rnd(8000,60000),3],dance:[4,rnd(15000,130000),6],teaser:[5,rnd(20000,160000),7],travel:[3,rnd(9000,90000),4],fans:[2,rnd(5000,50000),2]}[k],likes=Math.floor(x[1]*(1+S.socialMedia/100)),fans=Math.floor(likes*(.025+S.fame/5000));S.likesToday+=likes;S.followers+=fans;S.engagement=clamp(x[2]+rnd(-2,5));chg({energy:-5,fame:x[0],socialMedia:2,happiness:2,stress:2});note('YOUR POST WENT VIRAL!',`♥ ${fmt(likes)} likes • +${fmt(fans)} followers • Fame +${x[0]}`);advanceDay()}
function travel(to){let p=PLACES[to];if(!p||to===S.location)return;if(S.money<p[0])return note('NOT ENOUGH FUNDS','You cannot afford this fictional trip.');cash(-p[0],'Travel to '+to);S.location=to;chg({energy:-8,happiness:8,stress:2,fame:Math.floor(p[3]/2)});note('ARRIVED IN '+to.toUpperCase(),`Fashion ★${p[1]} · Music ★${p[2]} · Entertainment ★${p[3]}`);advanceDay()}
function interact(i,k){let p=S.relationships[i];if(!p)return;let e={hang:[4,7,1],collab:[2,2,8],practice:[1,4,9]}[k]||[2,5,2];p.trust=clamp(p.trust+e[0]);p.friendship=clamp(p.friendship+e[1]);p.chemistry=clamp(p.chemistry+e[2]);chg({energy:-4,happiness:3,stress:-2,fame:k==='collab'?2:0});people();note('SOCIAL CIRCLE',`${p.name}: connection improved.`)}
function event(){let es=[['SURPRISE VIRAL SONG','A fictional track catches on across social platforms.',()=>{chg({fame:5,socialMedia:4});S.followers+=rnd(20000,80000)}],['SOLD-OUT CONCERT','A fictional promoter reports a sold-out show.',()=>{cash(rnd(25000,80000),'Sold-out concert');chg({fame:5,happiness:6,stress:8})}],['FASHION OPPORTUNITY','A fictional fashion house invites your avatar to a campaign.',()=>{cash(rnd(30000,100000),'Fictional fashion offer');chg({fashionSkill:3,fame:4,reputation:4,energy:-8})}],['ACTING OFFER','A fictional studio requests an audition.',()=>chg({actingSkill:4,fame:3,stress:5})],['SCHEDULE CONFLICT','Two fictional commitments overlap.',()=>chg({energy:-5,stress:4,fame:2})],['FAN MILESTONE','Your fictional audience reaches a new milestone.',()=>{let n=rnd(10000,50000);S.followers+=n;chg({happiness:7,reputation:2});note('FAN MILESTONE','+'+fmt(n)+' followers.') }]];let e=es[rnd(0,es.length-1)];S.notifications.unshift({title:e[0],text:e[1],date:label(),unread:true});S.notifications=S.notifications.slice(0,20);document.getElementById('oppTitle').textContent=e[0];document.getElementById('oppText').textContent=e[1];document.getElementById('oppAccept').onclick=()=>{e[2]();close('opportunityModal');S.notifications[0].unread=false;ui()};document.getElementById('oppDecline').onclick=()=>{close('opportunityModal');S.notifications[0].unread=false;ui()};open('opportunityModal')}
function milestones(){let n=LEVELS.reduce((x,l,i)=>S.fame>=l[1]?i+1:x,1);if(n>S.careerLevel){S.careerLevel=n;let l=LEVELS[n-1];document.getElementById('milestoneTitle').textContent=l[0].toUpperCase();document.getElementById('milestoneText').textContent=`Your career has reached a new level. ${l[2]}.`;open('milestoneModal');note('LEVEL UP',`You reached ${l[0]}.`)}}
function open(id){document.getElementById(id).classList.remove('hidden')} function close(id){document.getElementById(id).classList.add('hidden')}
function toast(t,x){let d=document.createElement('div');d.className='toast';d.innerHTML=`<b>${t}</b><span>${x}</span>`;document.getElementById('toastStack').appendChild(d);setTimeout(()=>d.remove(),4200)}
function save(silent=false){localStorage.setItem(KEY,JSON.stringify(S));if(!silent)note('GAME SAVED','Your fictional career was saved locally.')}
function load(){let r=localStorage.getItem(KEY);if(!r)return note('NO SAVE FOUND','Save your game first.');try{Object.assign(S,JSON.parse(r));ui();note('GAME LOADED','Local save restored.')}catch(e){note('LOAD FAILED','The local save could not be read.')}}
function reset(){if(confirm('Start a new fictional career?')){localStorage.removeItem(KEY);location.reload()}}
function section(id){document.querySelectorAll('.game-section').forEach(x=>x.classList.toggle('active-section',x.id===id));document.querySelectorAll('[data-section]').forEach(x=>x.classList.toggle('active',x.dataset.section===id));scrollTo({top:0,behavior:'smooth'})}
function stats(){document.getElementById('statGrid').innerHTML=STATS.map(s=>{let v=S[s[0]],p=s[0]==='money'?Math.min(100,v/50000):v;return `<div class="stat-card"><div class="stat-top"><span class="stat-name">${s[1]} ${s[2]}</span><span class="stat-value">${s[0]==='money'?'$'+fmt(v):v}</span></div><div class="bar"><i style="width:${p}%"></i></div></div>`}).join('')}
function schedule(){let d=date().getDay(),a=d===0||d===6?[['11:00','Creative Planning','Career'],['16:00','Fan Interaction','Social'],['20:00','Private Time','Lifestyle']]:[['10:00','Dance Practice','Training'],['14:00','Photoshoot','Fashion'],['19:30','Studio Session','Music']];document.getElementById('scheduleList').innerHTML=a.map(x=>`<div class="schedule-item"><span class="schedule-time">${x[0]}</span><i class="schedule-dot"></i><div><b>${x[1]}</b><small>${x[2]}</small></div></div>`).join('')}
function career(){document.getElementById('careerStatus').textContent=LEVELS[S.careerLevel-1][0];document.getElementById('careerLevel').textContent=S.careerLevel;document.getElementById('careerLadder').innerHTML=LEVELS.map((l,i)=>`<div class="ladder-item ${i<S.careerLevel?'unlocked':''} ${i===S.careerLevel-1?'current':''}"><div class="ladder-number">${i+1}</div><div class="ladder-copy"><b>${l[0]}</b><small>Fame ${l[1]}+ • ${l[2]}</small></div></div>`).join('');let keys=['rehearsal','concert','fanmeet','interview','photoshoot','campaign','audition','acting','fashionweek','luxury','magazine','redcarpet'];document.getElementById('careerActions').innerHTML=keys.map(k=>{let a=A[k],min=k==='concert'?40:k==='acting'?55:k==='luxury'?80:k==='fashionweek'?70:20;return `<button class="action-btn" data-action="${k}" ${S.fame>=min?'':'disabled'}><span><b>${a[0]}</b><small>${a[2]} • Unlock: Fame ${min}</small></span><span>${S.fame>=min?'PLAY':'LOCKED'}</span></button>`}).join('')}
function activities(){let keys=Object.keys(A);document.getElementById('activityList').innerHTML=keys.map(k=>{let a=A[k],min=k==='concert'?40:k==='acting'?55:k==='luxury'?80:0;return `<button class="activity-btn" data-action="${k}" ${S.fame>=min?'':'disabled'}><span class="activity-info"><b>${a[0]}</b><small>${a[1]}</small></span><span class="activity-impact">${a[2]}</span></button>`}).join('')}
function travelUI(){document.getElementById('travelGrid').innerHTML=Object.keys(PLACES).map(n=>{let p=PLACES[n];return `<button class="travel-place" data-travel="${n}" ${n===S.location?'disabled':''}><b>${n}</b><small>${n===S.location?'CURRENT LOCATION':'Travel $'+fmt(p[0])}</small><em>Fashion ★${p[1]} · Music ★${p[2]} · Entertainment ★${p[3]}</em></button>`}).join('')}
function people(){document.getElementById('peopleList').innerHTML=S.relationships.map((p,i)=>`<div class="person"><div class="person-head"><div><b>${p.name}</b><small>${p.role}</small></div><span>♡</span></div><div class="relationship-bars"><div class="relationship-line">Trust <i style="--v:${p.trust}%"></i></div><div class="relationship-line">Friendship <i style="--v:${p.friendship}%"></i></div><div class="relationship-line">Chemistry <i style="--v:${p.chemistry}%"></i></div></div><div class="person-actions"><button class="ghost-btn" data-person="${i}" data-kind="hang">Hang Out</button><button class="ghost-btn" data-person="${i}" data-kind="collab">Collaborate</button><button class="ghost-btn" data-person="${i}" data-kind="practice">Practice</button></div></div>`).join('')}
function socialUI(){document.getElementById('followersValue').textContent=fmt(S.followers);document.getElementById('likesValue').textContent=fmt(S.likesToday);document.getElementById('engagementValue').textContent=S.engagement+'%';document.getElementById('socialRepValue').textContent=S.reputation;document.getElementById('socialActions').innerHTML=[['photo','Post Photo'],['dance','Post Dance Video'],['teaser','Post Music Teaser'],['travel','Post Travel Update'],['fans','Interact With Fans']].map(x=>`<button class="action-btn" data-social="${x[0]}"><span><b>${x[1]}</b><small>Energy −5 • audience engagement</small></span><span>POST →</span></button>`).join('')}
function music(){let s=S.currentSong;document.getElementById('currentSong').innerHTML=s?`<div class="song-card"><b>${s.title}</b><small>${s.genre} • ${s.recorded?'Recorded — ready to release':'Draft — needs recording'}</small></div>`:'<div class="muted">No song in production.</div>';document.getElementById('releaseList').innerHTML=S.releases.length?S.releases.map(r=>`<div class="release-item"><b>${r.title}</b><small>${r.genre} • ${r.date} • Review: ${r.review}</small><div class="release-stats"><div><b>${fmt(r.streams)}</b><span>STREAMS</span></div><div><b>+${fmt(r.fans)}</b><span>FANS</span></div><div><b>$${fmt(r.revenue)}</b><span>REVENUE</span></div><div><b>+${r.fameGain}</b><span>FAME</span></div></div></div>`).join(''):'<div class="muted">No fictional releases yet.</div>'}
function transactions(){let h=S.transactions.slice(0,12).map(t=>`<div class="transaction"><div>${t.reason}<small>${t.date}</small></div><b class="${t.amount>=0?'income':'expense'}">${t.amount>=0?'+':'−'} $${fmt(Math.abs(t.amount))}</b></div>`).join('');document.getElementById('transactionMini').innerHTML=S.transactions.slice(0,4).map(t=>`<div class="transaction"><div>${t.reason}</div><b class="${t.amount>=0?'income':'expense'}">${t.amount>=0?'+':'−'} $${fmt(Math.abs(t.amount))}</b></div>`).join('')||'<div class="muted">No transactions yet.</div>';document.getElementById('transactionHistory').innerHTML=h||'<div class="muted">No transactions yet.</div>';document.getElementById('financeTotal').textContent='$'+fmt(S.money);document.getElementById('moneyValue').textContent='$'+fmt(S.money)}
function ui(){document.getElementById('dayCount').textContent='DAY '+S.totalDays;document.getElementById('weekday').textContent=DAYS[date().getDay()].toUpperCase();document.getElementById('dateText').textContent=longDate();document.getElementById('locationText').textContent=S.location;document.getElementById('profileLocation').textContent=S.location;document.getElementById('ageValue').textContent=S.age;stats();schedule();career();activities();travelUI();people();socialUI();music();transactions();document.getElementById('notificationDot').classList.toggle('hidden',!S.notifications.some(n=>n.unread))}
document.addEventListener('click',e=>{let x=e.target.closest('[data-section]');if(x)return section(x.dataset.section);x=e.target.closest('[data-action]');if(x)return doAction(x.dataset.action);x=e.target.closest('[data-advance]');if(x)return advanceDay(+x.dataset.advance);x=e.target.closest('[data-travel]');if(x)return travel(x.dataset.travel);x=e.target.closest('[data-social]');if(x)return social(x.dataset.social);x=e.target.closest('[data-person]');if(x)return interact(+x.dataset.person,x.dataset.kind);x=e.target.closest('[data-close-modal]');if(x)close(x.dataset.closeModal)});
document.getElementById('saveBtn').onclick=()=>save();document.getElementById('loadBtn').onclick=load;document.getElementById('resetBtn').onclick=reset;document.getElementById('notificationBtn').onclick=()=>{let n=S.notifications.find(n=>n.unread)||S.notifications[0];if(n){n.unread=false;ui();note(n.title,n.text)}else note('NOTIFICATIONS','No new fictional opportunities.')};document.querySelectorAll('[data-music-action]').forEach(b=>b.onclick=()=>b.dataset.musicAction==='create'?createSong():b.dataset.musicAction==='record'?recordSong():releaseSong());
if(localStorage.getItem(KEY)){try{Object.assign(S,JSON.parse(localStorage.getItem(KEY)))}catch(e){}}else S.transactions=[{amount:100000,reason:'Starting balance',date:label()}];ui();setTimeout(()=>note('WELCOME TO LISA LIFE SIMULATOR','A fictional career-management sandbox. Build a sustainable global entertainment career.'),500);