/* LISA MANOBAN — LIFE SIMULATOR
   Fictionalized career-management gameplay. All events, relationships,
   schedules, finances, reviews and private-life situations are game mechanics. */

const STORAGE_KEY = 'lisaLifeSimulatorSaveV1';
const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];
const WEEKDAYS = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const CAREER_LEVELS = [
  {name:'Trainee', min:0, unlock:'Training, practice and small opportunities'},
  {name:'Rising Artist', min:20, unlock:'More creative and media work'},
  {name:'Idol', min:40, unlock:'Concerts, campaigns and releases'},
  {name:'Solo Artist', min:55, unlock:'Solo releases and major campaigns'},
  {name:'International Star', min:70, unlock:'Global tours and international projects'},
  {name:'Global Superstar', min:85, unlock:'Elite fictional global opportunities'},
  {name:'Entertainment Icon', min:96, unlock:'Legacy projects and premium events'}
];

const LOCATIONS = {
  Seoul:{cost:0, time:0, fashion:3, music:5, entertainment:5}, Bangkok:{cost:1200,time:1,fashion:2,music:4,entertainment:4}, Paris:{cost:8500,time:1,fashion:5,music:3,entertainment:4},
  Milan:{cost:7600,time:1,fashion:5,music:3,entertainment:3}, London:{cost:6200,time:1,fashion:4,music:5,entertainment:4}, 'New York':{cost:7200,time:1,fashion:4,music:5,entertainment:5},
  'Los Angeles':{cost:6800,time:1,fashion:4,music:5,entertainment:5}, Tokyo:{cost:5400,time:1,fashion:4,music:4,entertainment:5}, Dubai:{cost:5000,time:1,fashion:5,music:3,entertainment:4}
};

const gameState = {
  day:1, month:1, year:2026, age:20, location:'Seoul', money:100000, fame:25, happiness:80, energy:90, stress:10,
  musicSkill:60, danceSkill:85, fashionSkill:70, actingSkill:40, socialMedia:55, followers:500000, likesToday:0, engagement:0,
  reputation:70, careerLevel:2, totalDays:1, currentSong:null, releases:[], transactions:[], notifications:[], relationships:[
    {name:'Mina Park',role:'Dance Director',trust:64,friendship:70,chemistry:78},
    {name:'Evan Cole',role:'Fictional Producer',trust:58,friendship:49,chemistry:84},
    {name:'Nora Kim',role:'Fashion Editor',trust:72,friendship:61,chemistry:67},
    {name:'Jae Han',role:'Fictional Actor',trust:55,friendship:66,chemistry:60}
  ]
};

const STAT_DEFS = [
  ['happiness','❤️','Happiness','happiness'],['energy','⚡','Energy','energy'],['fame','⭐','Fame','fame'],['musicSkill','🎤','Music Skill','musicSkill'],['danceSkill','💃','Dance Skill','danceSkill'],
  ['fashionSkill','👗','Fashion','fashionSkill'],['actingSkill','🎬','Acting','actingSkill'],['socialMedia','📱','Social Media','socialMedia'],['money','💰','Money','money'],['stress','🧠','Stress','stress']
];

const ACTIVITIES = {
  record:{name:'Record Song',cat:'Music',impact:'Energy −12 • Music +2',cost:0,run(){change({energy:-12,musicSkill:2,stress:4}); toast('STUDIO SESSION','A focused recording session improved your music craft.');}},
  vocals:{name:'Practice Vocals',cat:'Music',impact:'Energy −8 • Music +3',cost:0,run(){change({energy:-8,musicSkill:3,stress:2});}},
  write:{name:'Write Music',cat:'Music',impact:'Energy −6 • Music +2 • Happiness +2',cost:0,run(){change({energy:-6,musicSkill:2,happiness:2,stress:1});}},
  dance:{name:'Dance Practice',cat:'Dance',impact:'Energy −15 • Dance +3 • Fame +1',cost:0,run(){change({energy:-15,danceSkill:3,fame:1,stress:5});}},
  choreo:{name:'Choreography',cat:'Dance',impact:'Energy −12 • Dance +4 • Music +1',cost:0,run(){change({energy:-12,danceSkill:4,musicSkill:1,stress:5});}},
  rehearsal:{name:'Rehearsal',cat:'Career',impact:'Energy −18 • Fame +2 • Stress +7',cost:0,run(){change({energy:-18,fame:2,stress:7});}},
  concert:{name:'Concert',cat:'Career',impact:'Energy −25 • Fame +6 • Income',cost:0,run(){const income=rand(18000,90000)+gameState.fame*700; change({energy:-25,fame:6,happiness:5,stress:12}); money(income,'Concert'); toast('SHOW NIGHT',`The fictional concert drew a huge crowd. +$${fmt(income)}.`);}},
  fanmeet:{name:'Fan Meeting',cat:'Career',impact:'Energy −12 • Fame +2 • Followers',cost:0,run(){const fans=rand(3000,18000);change({energy:-12,fame:2,happiness:6,stress:3});gameState.followers+=fans;toast('FAN MILESTONE',`A warm fan event brought +${fmt(fans)} followers.`);}},
  interview:{name:'Interview',cat:'Career',impact:'Energy −8 • Fame +2 • Reputation',cost:0,run(){change({energy:-8,fame:2,reputation:2,stress:3});}},
  photoshoot:{name:'Photoshoot',cat:'Fashion',impact:'Energy −10 • Fashion +3 • Fame +2',cost:0,run(){change({energy:-10,fashionSkill:3,fame:2,reputation:1,stress:4});}},
  campaign:{name:'Brand Campaign',cat:'Fashion',impact:'Energy −14 • Fame +4 • Income',cost:0,run(){const income=rand(25000,140000)+gameState.fashionSkill*500;change({energy:-14,fame:4,reputation:3,stress:8});money(income,'Fictional campaign');toast('CAMPAIGN COMPLETE',`The fictional campaign paid $${fmt(income)}.`);}},
  audition:{name:'Audition',cat:'Acting',impact:'Energy −10 • Acting +2 • Stress +4',cost:0,run(){change({energy:-10,actingSkill:2,stress:4});if(Math.random()<.35){change({fame:3});toast('CALLBACK','A fictional casting team requested a second meeting.');}}},
  acting:{name:'Acting Project',cat:'Acting',impact:'Energy −20 • Acting +5 • Fame +5 • Income',cost:0,run(){const income=rand(20000,110000);change({energy:-20,actingSkill:5,fame:5,stress:9});money(income,'Acting project');}},
  fashionweek:{name:'Fashion Week',cat:'Fashion',impact:'Energy −18 • Fashion +4 • Fame +5',cost:0,run(){change({energy:-18,fashionSkill:4,fame:5,reputation:4,stress:10});}},
  luxury:{name:'Luxury Campaign',cat:'Fashion',impact:'Energy −15 • Fashion +4 • Fame +4 • Income',cost:0,run(){const income=rand(50000,180000);change({energy:-15,fashionSkill:4,fame:4,reputation:4,stress:8});money(income,'Luxury campaign');}},
  magazine:{name:'Magazine Cover',cat:'Fashion',impact:'Energy −8 • Fashion +2 • Fame +3',cost:0,run(){change({energy:-8,fashionSkill:2,fame:3,reputation:3,stress:3});}},
  redcarpet:{name:'Red Carpet',cat:'Fashion',impact:'Energy −10 • Fame +3 • Reputation +3',cost:0,run(){change({energy:-10,fame:3,reputation:3,stress:5);}},
  rest:{name:'Rest',cat:'Lifestyle',impact:'Energy +28 • Stress −12 • Happiness +5',cost:0,run(){change({energy:28,stress:-12,happiness:5});}},
  exercise:{name:'Exercise',cat:'Lifestyle',impact:'Energy −7 • Stress −5 • Happiness +4',cost:0,run(){change({energy:-7,stress:-5,happiness:4});}},
  shopping:{name:'Shopping',cat:'Lifestyle',impact:'Money −$3,200 • Happiness +6',cost:3200,run(){if(gameState.money<3200)return insufficient();money(-3200,'Shopping');change({happiness:6,stress:-2});}},
  friends:{name:'Spend Time With Friends',cat:'Lifestyle',impact:'Energy −5 • Happiness +9 • Stress −7',cost:0,run(){change({energy:-5,happiness:9,stress:-7});}},
  private:{name:'Private Time',cat:'Lifestyle',impact:'Energy +8 • Happiness +6 • Stress −10',cost:0,run(){change({energy:8,happiness:6,stress:-10});}},
  travel:{name:'Travel',cat:'Lifestyle',impact:'Choose a destination below',cost:0,run(){showSection('lifestyle');toast('WORLD MAP','Choose a destination to travel.');}}
};

function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function clamp(n){return Math.max(0,Math.min(100,Math.round(n)))}
function fmt(n){return Math.round(n).toLocaleString('en-US')}
function money(n,reason){gameState.money=Math.max(0,gameState.money+n);gameState.transactions.unshift({amount:n,reason,date:dateLabel()});gameState.transactions=gameState.transactions.slice(0,40);updateUI()}
function change(delta){Object.keys(delta).forEach(k=>{if(k==='money'||k==='followers'||k==='likesToday')gameState[k]+=delta[k];else if(k in gameState)gameState[k]=clamp(gameState[k]+delta[k])});gameState.energy=clamp(gameState.energy);gameState.stress=clamp(gameState.stress);updateUI();checkMilestones()}
function insufficient(){toast('NOT ENOUGH FUNDS','This fictional expense is currently outside your virtual balance.');return false}
function dateObj(){return new Date(gameState.year,gameState.month-1,gameState.day)}
function dateLabel(){const d=dateObj();return `${MONTHS[d.getMonth()].slice(0,3)} ${d.getDate()}, ${d.getFullYear()}`}
function longDate(){const d=dateObj();return `${d.getDate()} ${MONTHS[d.getMonth()].toUpperCase()} ${d.getFullYear()}`}
function advanceDay(days=1,quiet=false){for(let i=0;i<days;i++){const d=dateObj();d.setDate(d.getDate()+1);gameState.day=d.getDate();gameState.month=d.getMonth()+1;gameState.year=d.getFullYear();gameState.totalDays++;if(gameState.totalDays%365===0)gameState.age++;gameState.energy=clamp(gameState.energy+8);gameState.stress=clamp(gameState.stress-3);gameState.happiness=clamp(gameState.happiness-1);gameState.likesToday=0;dailyTick()}updateUI();if(!quiet)toast('TIME ADVANCED',`You moved forward ${days===1?'one day':days+' days'}.`);saveGame(true)}
function dailyTick(){if(Math.random()<.18)generateEvent();if(Math.random()<.08){const upkeep=1200;money(-upkeep,'Staff & lifestyle');}if(gameState.energy<15)change({stress:3,happiness:-3})}

function performActivity(key){const a=ACTIVITIES[key];if(!a)return;if(gameState.energy<=0&&key!=='rest'){toast('TOO EXHAUSTED','Rest before taking another demanding action.');return}if(a.cost&&gameState.money<a.cost){insufficient();return}a.run();if(key!=='travel'&&key!=='rest')advanceDay(1,true);toast(a.name.toUpperCase(),'Action completed. Check your updated stats.');}

function releaseSong(){if(!gameState.currentSong){toast('NO SONG READY','Create and record a song first.');return}if(gameState.currentSong.recorded===false){toast('RECORD FIRST','Your song needs a recording before release.');return}if(gameState.energy<12){toast('TOO EXHAUSTED','Rest before releasing a project.');return}const s=gameState.currentSong;const quality=clamp((gameState.musicSkill+s.genreBonus+gameState.fame*.35)+rand(-10,12));const streams=Math.max(10000,Math.floor((quality+gameState.fame)*rand(180000,520000)));const fans=Math.floor(streams*(0.001+gameState.socialMedia/100000));const revenue=Math.floor(streams*.0022);const fameGain=Math.max(2,Math.floor(quality/15));const review=quality>82?'Acclaimed':quality>65?'Strong':'Mixed';gameState.releases.unshift({title:s.title,genre:s.genre,streams,fans,revenue,fameGain,review,date:dateLabel()});gameState.releases=gameState.releases.slice(0,12);gameState.followers+=fans;change({energy:-12,fame:fameGain,happiness:5,stress:8});money(revenue,'Music release');gameState.currentSong=null;toast('NEW SINGLE RELEASED',`“${s.title}” reached ${fmt(streams)} fictional streams. +$${fmt(revenue)} • +${fmt(fans)} fans.`);advanceDay(1,true);renderMusic()}
function createSong(){const title=document.getElementById('songTitle').value.trim()||'Untitled Track';const genre=document.getElementById('songGenre').value;gameState.currentSong={title,genre,genreBonus:rand(0,8),recorded:false};renderMusic();toast('SONG CREATED',`“${title}” is ready for recording.`)}
function recordSong(){if(!gameState.currentSong){toast('CREATE A SONG','Give your next fictional release a title first.');return}if(gameState.energy<10){toast('TOO EXHAUSTED','Rest before recording.');return}gameState.currentSong.recorded=true;change({energy:-10,musicSkill:2,stress:5});toast('RECORDING COMPLETE',`“${gameState.currentSong.title}” is ready for release.`);renderMusic()}

function postSocial(type){if(gameState.energy<5){toast('TOO EXHAUSTED','Rest before posting.');return}const base={photo:[2,rand(8000,60000),3],dance:[4,rand(15000,130000),6],teaser:[5,rand(20000,160000),7],travel:[3,rand(9000,90000),4],fans:[2,rand(5000,50000),2]}[type];const likes=Math.floor(base[1]*(1+gameState.socialMedia/100));const fans=Math.floor(likes*(.025+gameState.fame/5000));gameState.likesToday+=likes;gameState.followers+=fans;gameState.engagement=clamp(base[2]+rand(-2,5));change({energy:-5,fame:base[0],socialMedia:2,happiness:2,stress:2});toast('YOUR POST WENT VIRAL!',`♥ ${fmt(likes)} likes • +${fmt(fans)} followers • Fame +${base[0]}`);advanceDay(1,true)}

function travel(destination){const place=LOCATIONS[destination];if(!place||destination===gameState.location)return;if(gameState.money<place.cost)return insufficient();money(-place.cost,`Travel to ${destination}`);gameState.location=destination;change({energy:-8,happiness:8,stress:2,fame:Math.floor(place.entertainment/2)});toast(`ARRIVED IN ${destination.toUpperCase()}`,`Fashion ★${place.fashion} • Music ★${place.music} • Entertainment ★${place.entertainment}`);advanceDay(Math.max(1,place.time),true)}

function interact(i,kind){const p=gameState.relationships[i];if(!p)return;const effects={hang:[4,7,1],collab:[2,2,8],practice:[1,4,9],event:[3,5,5],message:[2,5,2]}[kind];p.trust=clamp(p.trust+effects[0]);p.friendship=clamp(p.friendship+effects[1]);p.chemistry=clamp(p.chemistry+effects[2]);change({energy:-4,happiness:3,stress:-2,fame:kind==='collab'?2:0});toast('SOCIAL CIRCLE',`${p.name}: trust and connection improved.`);renderPeople()}

function generateEvent(){const events=[
  {title:'SURPRISE VIRAL SONG',text:'A fictional track catches on unexpectedly across social platforms.',accept(){change({fame:5,socialMedia:4});gameState.followers+=rand(20000,80000);}},
  {title:'SOLD-OUT CONCERT',text:'A fictional promoter reports that your next show has sold out.',accept(){money(rand(25000,80000),'Sold-out concert');change({fame:5,happiness:6,stress:8});}},
  {title:'FASHION OPPORTUNITY',text:'A fictional fashion house invites your career avatar to a campaign.',accept(){money(rand(30000,100000),'Fictional fashion offer');change({fashionSkill:3,fame:4,reputation:4,energy:-8});},decline(){change({stress:-2});}},
  {title:'ACTING OFFER',text:'A fictional studio wants you to audition for a supporting role.',accept(){change({actingSkill:4,fame:3,stress:5});toast('AUDITION BOOKED','A fictional audition has been added to your career path.');},decline(){change({happiness:1});}},
  {title:'SCHEDULE CONFLICT',text:'Two fictional commitments overlap. Protecting your energy means declining one.',accept(){change({energy:-5,stress:4,fame:2});},decline(){change({energy:4,stress:-3});}},
  {title:'FAN MILESTONE',text:'Your audience reaches a new fictional follower milestone.',accept(){const gain=rand(10000,50000);gameState.followers+=gain;change({happiness:7,reputation:2});toast('FAN MILESTONE',`+${fmt(gain)} followers.`);}}
];const e=events[rand(0,events.length-1)];gameState.notifications.unshift({title:e.title,text:e.text,date:dateLabel(),unread:true});gameState.notifications=gameState.notifications.slice(0,20);showOpportunity(e)}
function showOpportunity(e){document.getElementById('oppTitle').textContent=e.title;document.getElementById('oppText').textContent=e.text;document.getElementById('oppAccept').onclick=()=>{e.accept();closeModal('opportunityModal');gameState.notifications[0].unread=false;updateUI()};document.getElementById('oppDecline').onclick=()=>{if(e.decline)e.decline();closeModal('opportunityModal');gameState.notifications[0].unread=false;updateUI()};openModal('opportunityModal')}

function checkMilestones(){const newLevel=CAREER_LEVELS.reduce((acc,l,i)=>gameState.fame>=l.min?i+1:acc,1);if(newLevel>gameState.careerLevel){gameState.careerLevel=newLevel;const level=CAREER_LEVELS[newLevel-1];document.getElementById('milestoneTitle').textContent=level.name.toUpperCase();document.getElementById('milestoneText').textContent=`Your career has reached a new level. ${level.unlock}.`;openModal('milestoneModal');toast('LEVEL UP',`You reached ${level.name}.`);}}

function schedule(){const pools=[['10:00','Dance Practice','Training'],['14:00','Photoshoot','Fashion'],['19:30','Studio Session','Music']];const d=dateObj().getDay();return d===0||d===6?[['11:00','Creative Planning','Career'],['16:00','Fan Interaction','Social'],['20:00','Private Time','Lifestyle']]:pools}
function renderSchedule(){document.getElementById('scheduleList').innerHTML=schedule().map(x=>`<div class="schedule-item"><span class="schedule-time">${x[0]}</span><i class="schedule-dot"></i><div><b>${x[1]}</b><small>${x[2]}</small></div></div>`).join('')}
function renderStats(){const el=document.getElementById('statGrid');el.innerHTML=STAT_DEFS.map(([key,icon,name])=>{const val=key==='money'?gameState.money:gameState[key];const shown=key==='money'?'$'+fmt(val):val;const pct=key==='money'?Math.min(100,gameState.money/50000):val;return `<div class="stat-card" title="${statTip(name)}"><div class="stat-top"><span class="stat-name">${icon} ${name}</span><span class="stat-value" data-stat="${key}">${shown}</span></div><div class="bar"><i style="width:${pct}%"></i></div></div>`}).join('')}
function statTip(n){return {Happiness:'Overall mood and satisfaction.',Energy:'Capacity for demanding actions.',Fame:'Career visibility and unlock progress.', 'Music Skill':'Songwriting, vocals and recording ability.','Dance Skill':'Dance and choreography ability.',Fashion:'Fictional fashion-career reputation.',Acting:'Performance and acting ability.','Social Media':'Content and audience engagement skill.',Money:'Virtual game currency.',Stress:'Pressure level; lower is generally easier to manage.'}[n]||''}
function renderCareer(){document.getElementById('careerStatus').textContent=CAREER_LEVELS[gameState.careerLevel-1].name;document.getElementById('careerLevel').textContent=gameState.careerLevel;document.getElementById('careerLadder').innerHTML=CAREER_LEVELS.map((l,i)=>`<div class="ladder-item ${i<gameState.careerLevel?'unlocked':''} ${i===gameState.careerLevel-1?'current':''}"><div class="ladder-number">${i+1}</div><div class="ladder-copy"><b>${l.name}</b><small>Fame ${l.min}+ • ${l.unlock}</small></div></div>`).join('');const next=CAREER_LEVELS[gameState.careerLevel];document.getElementById('nextLevelText').textContent=next?`${Math.max(0,next.min-gameState.fame)} fame to ${next.name}`:'MAX LEVEL'}
function renderActions(){const unlocked=(min)=>gameState.fame>=min;const arr=[['rehearsal',1],['concert',40],['fanmeet',25],['interview',20],['photoshoot',20],['campaign',35],['audition',30],['acting',55],['fashionweek',70],['luxury',80],['magazine',50],['redcarpet',45]];document.getElementById('careerActions').innerHTML=arr.map(([k,min])=>{const a=ACTIVITIES[k];return `<button class="action-btn" ${unlocked(min)?'':'disabled'} data-action="${k}"><span><b>${a.name}</b><small>${a.impact} • Unlock: Fame ${min}</small></span><span class="action-cost">${unlocked(min)?'PLAY':'LOCKED'}</span></button>`}).join('')}
function renderActivities(){const arr=['record','vocals','write','dance','choreo','rehearsal','concert','fanmeet','interview','photoshoot','campaign','audition','acting','fashionweek','luxury','magazine','redcarpet','rest','exercise','shopping','friends','private'];document.getElementById('activityList').innerHTML=arr.map(k=>{const a=ACTIVITIES[k];const min=k==='concert'?40:k==='acting'?55:k==='luxury'?80:0;return `<button class="activity-btn" ${gameState.fame>=min?'':'disabled'} data-action="${k}"><span class="activity-info"><b>${a.name}</b><small>${a.cat}</small></span><span class="activity-impact">${a.impact}</span></button>`}).join('')}
function renderTravel(){document.getElementById('travelGrid').innerHTML=Object.entries(LOCATIONS).map(([name,p])=>`<button class="travel-place" ${name===gameState.location?'disabled':''} data-travel="${name}"><b>${name}</b><small>${name===gameState.location?'CURRENT LOCATION':'Travel $'+fmt(p.cost)}</small><em>Fashion ★${p.fashion} · Music ★${p.music} · Entertainment ★${p.entertainment}</em></button>`).join('')}
function renderPeople(){document.getElementById('peopleList').innerHTML=gameState.relationships.map((p,i)=>`<div class="person"><div class="person-head"><div><b>${p.name}</b><small>${p.role}</small></div><span>♡</span></div><div class="relationship-bars"><div class="relationship-line">Trust <i style="--v:${p.trust}%"></i></div><div class="relationship-line">Friendship <i style="--v:${p.friendship}%"></i></div><div class="relationship-line">Chemistry <i style="--v:${p.chemistry}%"></i></div></div><div class="person-actions"><button class="ghost-btn" data-person="${i}" data-kind="hang">Hang Out</button><button class="ghost-btn" data-person="${i}" data-kind="collab">Collaborate</button><button class="ghost-btn" data-person="${i}" data-kind="practice">Practice</button></div></div>`).join('')}
function renderSocial(){document.getElementById('followersValue').textContent=fmt(gameState.followers);document.getElementById('likesValue').textContent=fmt(gameState.likesToday);document.getElementById('engagementValue').textContent=gameState.engagement+'%';document.getElementById('socialRepValue').textContent=gameState.reputation;const arr=[['photo','Post Photo'],['dance','Post Dance Video'],['teaser','Post Music Teaser'],['travel','Post Travel Update'],['fans','Interact With Fans']];document.getElementById('socialActions').innerHTML=arr.map(([k,n])=>`<button class="action-btn" data-social="${k}"><span><b>${n}</b><small>Energy −5 • audience engagement</small></span><span>POST →</span></button>`).join('')}
function renderMusic(){const s=gameState.currentSong;document.getElementById('currentSong').innerHTML=s?`<div class="song-card"><b>${s.title}</b><small>${s.genre} • ${s.recorded?'Recorded — ready to release':'Draft — needs recording'}</small></div>`:'<div class="muted">No song in production.</div>';document.getElementById('releaseList').innerHTML=gameState.releases.length?gameState.releases.map(r=>`<div class="release-item"><b>${r.title}</b><small>${r.genre} • ${r.date} • Review: ${r.review}</small><div class="release-stats"><div><b>${fmt(r.streams)}</b><span>STREAMS</span></div><div><b>+${fmt(r.fans)}</b><span>FANS</span></div><div><b>$${fmt(r.revenue)}</b><span>REVENUE</span></div><div><b>+${r.fameGain}</b><span>FAME</span></div></div></div>`).join(''):'<div class="muted">Your fictional discography is empty. Create your first release.</div>'}
function renderTransactions(){const list=gameState.transactions.slice(0,10);document.getElementById('transactionMini').innerHTML=list.length?list.slice(0,4).map(t=>transactionHTML(t)).join(''):'<div class="muted">No transactions yet.</div>';document.getElementById('transactionHistory').innerHTML=list.length?list.map(t=>transactionHTML(t)).join(''):'<div class="muted">No transactions yet.</div>';document.getElementById('financeTotal').textContent='$'+fmt(gameState.money);document.getElementById('moneyValue').textContent='$'+fmt(gameState.money)}
function transactionHTML(t){return `<div class="transaction"><div><span>${t.reason}</span><small>${t.date}</small></div><b class="${t.amount>=0?'income':'expense'}">${t.amount>=0?'+':'−'} $${fmt(Math.abs(t.amount))}</b></div>`}
function renderNotifications(){document.getElementById('notificationDot').classList.toggle('hidden',!gameState.notifications.some(n=>n.unread))}
function updateUI(){document.getElementById('dayCount').textContent='DAY '+gameState.totalDays;document.getElementById('weekday').textContent=WEEKDAYS[dateObj().getDay()].toUpperCase();document.getElementById('dateText').textContent=longDate();document.getElementById('locationText').textContent=gameState.location;document.getElementById('profileLocation').textContent=gameState.location;document.getElementById('ageValue').textContent=gameState.age;document.getElementById('careerStatus').textContent=CAREER_LEVELS[gameState.careerLevel-1].name;document.getElementById('careerLevel').textContent=gameState.careerLevel;renderStats();renderSchedule();renderCareer();renderActions();renderActivities();renderTravel();renderPeople();renderSocial();renderMusic();renderTransactions();renderNotifications()}
function showSection(id){document.querySelectorAll('.game-section').forEach(s=>s.classList.toggle('active-section',s.id===id));document.querySelectorAll('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===id));window.scrollTo({top:0,behavior:'smooth'})}
function toast(title,text){const box=document.createElement('div');box.className='toast';box.innerHTML=`<b>${title}</b><span>${text}</span>`;document.getElementById('toastStack').appendChild(box);setTimeout(()=>box.remove(),4200)}
function openModal(id){document.getElementById(id).classList.remove('hidden')}
function closeModal(id){document.getElementById(id).classList.add('hidden')}
function saveGame(silent=false){localStorage.setItem(STORAGE_KEY,JSON.stringify(gameState));if(!silent)toast('GAME SAVED','Your fictional career has been saved locally in this browser.')}
function loadGame(){const raw=localStorage.getItem(STORAGE_KEY);if(!raw){toast('NO SAVE FOUND','Start playing and save your game first.');return}try{const data=JSON.parse(raw);Object.assign(gameState,data);updateUI();toast('GAME LOADED','Your local save is back on screen.')}catch(e){toast('LOAD FAILED','The local save could not be read.')}}
function newGame(){if(!confirm('Start a new fictional career? Your current local save will remain available until overwritten.'))return;localStorage.removeItem(STORAGE_KEY);location.reload()}

// Delegated interactions keep the UI modular and make dynamically-rendered buttons functional.
document.addEventListener('click',e=>{const section=e.target.closest('[data-section]');if(section){showSection(section.dataset.section);return}const action=e.target.closest('[data-action]');if(action){performActivity(action.dataset.action);return}const advance=e.target.closest('[data-advance]');if(advance){advanceDay(Number(advance.dataset.advance));return}const travelBtn=e.target.closest('[data-travel]');if(travelBtn){travel(travelBtn.dataset.travel);return}const social=e.target.closest('[data-social]');if(social){postSocial(social.dataset.social);return}const person=e.target.closest('[data-person]');if(person){interact(Number(person.dataset.person),person.dataset.kind);return}const close=e.target.closest('[data-close-modal]');if(close)closeModal(close.dataset.closeModal);});

document.getElementById('saveBtn').addEventListener('click',()=>saveGame());document.getElementById('loadBtn').addEventListener('click',loadGame);document.getElementById('resetBtn').addEventListener('click',newGame);document.getElementById('notificationBtn').addEventListener('click',()=>{const n=gameState.notifications[0];if(n){n.unread=false;updateUI();toast(n.title,n.text)}else toast('NOTIFICATIONS','No new fictional opportunities right now.')});
document.querySelectorAll('[data-music-action]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.musicAction;if(k==='create')createSong();if(k==='record')recordSong();if(k==='release')releaseSong()}));

// Initial local persistence + welcome transaction.
if(!localStorage.getItem(STORAGE_KEY)){gameState.transactions=[{amount:100000,reason:'Starting balance',date:dateLabel()}]}else{try{Object.assign(gameState,JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch(e){}}
updateUI();setTimeout(()=>toast('WELCOME TO LISA LIFE SIMULATOR','A fictional career-management sandbox. Build a sustainable global entertainment career.'),500);