require('dotenv').config();
const express=require('express');const path=require('path');const {init,run,all,get}=require('./database');const {seedCharacters,tick}=require('./simulation');const {chat}=require('./aiEngine');
const app=express();app.use(express.json());app.use(express.static(path.join(__dirname,'..','public')));
const now=()=>new Date().toISOString();
async function ensurePlayer(){const p=await get('SELECT * FROM player WHERE id=1');if(!p) await run('INSERT INTO player(id,username,display_name,bio,avatar,created_at) VALUES(1,?,?,?,?,?)',['newcreator','New Creator','Your story starts here.','YOU',now()]);}
app.get('/api/state',async(req,res)=>{try{const player=await get('SELECT * FROM player WHERE id=1');const feed=await all(`SELECT p.*,COALESCE(c.name,'You') author_name,COALESCE(c.avatar,'YOU') author_avatar FROM posts p LEFT JOIN characters c ON p.author_id=c.id ORDER BY datetime(p.created_at) DESC LIMIT 30`);const chars=await all('SELECT id,name,avatar,bio,archetype,followers,popularity,mood,relationships FROM characters ORDER BY followers DESC');const trends=await all('SELECT tag,MAX(score) score FROM trends GROUP BY tag ORDER BY score DESC LIMIT 8');const notifications=await all('SELECT * FROM notifications ORDER BY id DESC LIMIT 20');const messages=await all('SELECT * FROM messages ORDER BY id DESC LIMIT 60');const leaderboard=await all(`SELECT name,avatar,followers,popularity FROM characters UNION ALL SELECT display_name,avatar,followers,popularity FROM player ORDER BY followers DESC LIMIT 10`);const events=await all('SELECT * FROM events ORDER BY id DESC LIMIT 5');res.json({player,feed,chars,trends,notifications,messages,leaderboard,events});}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/onboarding',async(req,res)=>{const {username,displayName,bio,avatar}=req.body;await run('UPDATE player SET username=?,display_name=?,bio=?,avatar=? WHERE id=1',[username||'creator',displayName||'Creator',bio||'',avatar||'YOU']);res.json({ok:true})});
app.post('/api/posts',async(req,res)=>{const {text,hashtags=''}=req.body;if(!text?.trim())return res.status(400).json({error:'Write something first'});let vir=Math.random()*70+20;const followers=Math.floor((vir/100)*500+Math.random()*300);await run('INSERT INTO posts(author_id,author_type,text,hashtags,likes,comments,reposts,views,virality,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',['1','player',text,hashtags,0,0,0,Math.floor(vir*12),vir,now()]);await run('UPDATE player SET followers=followers+?,likes=likes+? WHERE id=1',[followers,Math.floor(vir)]);if(vir>78)await run('INSERT INTO notifications(text,icon,created_at) VALUES(?,?,?)',[`Your post is going viral — +${followers} followers!`,'🔥',now()]);res.json({ok:true,followersGained:followers,virality:vir})});
app.post('/api/chat',async(req,res)=>{try{const {characterId,message}=req.body;const c=await get('SELECT * FROM characters WHERE id=?',[characterId]);if(!c)return res.status(404).json({error:'Character not found'});const previous=await all('SELECT sender,text FROM messages WHERE character_id=? ORDER BY id DESC LIMIT 8',[characterId]);const reply=await chat(characterId.replace('ai_','').replace(/^00?/,'')==='1'?'aiko':characterId.includes('002')?'ren':characterId.includes('003')?'mika':'haru',message,JSON.stringify(previous));await run('INSERT INTO messages(character_id,sender,text,created_at) VALUES(?,?,?,?)',[characterId,'player',message,now()]);await run('INSERT INTO messages(character_id,sender,text,created_at) VALUES(?,?,?,?)',[characterId,'ai',reply,now()]);await run('INSERT INTO memories(character_id,memory,importance,created_at) VALUES(?,?,?,?)',[characterId,`Player said: ${message}`,1,now()]);res.json({reply})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/follow',async(req,res)=>{const c=await get('SELECT * FROM characters WHERE id=?',[req.body.characterId]);if(!c)return res.status(404).json({error:'Not found'});await run('UPDATE player SET following=following+1 WHERE id=1');await run('INSERT INTO notifications(text,icon,created_at) VALUES(?,?,?)',[`You followed ${c.name}`,'👤',now()]);res.json({ok:true})});
app.post('/api/like',async(req,res)=>{await run('UPDATE posts SET likes=likes+1 WHERE id=?',[req.body.postId]);res.json({ok:true})});
app.post('/api/comment',async(req,res)=>{await run('INSERT INTO comments(post_id,author_id,text,created_at) VALUES(?,?,?,?)',[req.body.postId,'1',req.body.text,now()]);await run('UPDATE posts SET comments=comments+1 WHERE id=?',[req.body.postId]);res.json({ok:true})});
app.post('/api/simulation/tick',async(req,res)=>{await tick();res.json({ok:true})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'..','public','index.html')));
(async()=>{await init();await ensurePlayer();await seedCharacters();await tick();setInterval(()=>tick().catch(console.error),90000);const port=process.env.PORT||3000;app.listen(port,()=>console.log(`OTAKUVERSE running on http://localhost:${port}`));})();
